name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускать конвейер только при изменениях в ветке main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настроить Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Логин в Docker Hub (если нужно публиковать образ)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Шаг 4: Собрать Docker-образ
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/your-app-name:latest .

      # Шаг 5: Запустить тесты
      - name: Run tests
        run: |
          docker run your-dockerhub-username/your-app-name:latest python -m pytest

      # Шаг 6: Публикация Docker-образа в Docker Hub
      - name: Push Docker image
        run: docker push your-dockerhub-username/your-app-name:latest

      # Шаг 7: Развертывание (пример для Kubernetes)
      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to Kubernetes..."
          # Здесь могут быть команды для применения манифестов Kubernetes
          # kubectl apply -f k8s-deployment.yaml